# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finmon1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import queries
import sqlite3

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(773, 463)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 771, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("Операции")
        self.debtor_combobox = QtWidgets.QComboBox(self.tab)
        self.debtor_combobox.setGeometry(QtCore.QRect(330, 30, 421, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debtor_combobox.sizePolicy().hasHeightForWidth())
        self.debtor_combobox.setSizePolicy(sizePolicy)
        self.debtor_combobox.setObjectName("debtor_combobox")
        self.receiver_combobox = QtWidgets.QComboBox(self.tab)
        self.receiver_combobox.setGeometry(QtCore.QRect(330, 80, 421, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiver_combobox.sizePolicy().hasHeightForWidth())
        self.receiver_combobox.setSizePolicy(sizePolicy)
        self.receiver_combobox.setObjectName("receiver_combobox")
        self.payer_combobox = QtWidgets.QComboBox(self.tab)
        self.payer_combobox.setGeometry(QtCore.QRect(330, 130, 421, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payer_combobox.sizePolicy().hasHeightForWidth())
        self.payer_combobox.setSizePolicy(sizePolicy)
        self.payer_combobox.setObjectName("payer_combobox")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(330, 10, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(330, 60, 71, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(330, 110, 91, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.operation_date_dateEdit = QtWidgets.QDateEdit(self.tab)
        self.operation_date_dateEdit.setGeometry(QtCore.QRect(40, 100, 111, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operation_date_dateEdit.sizePolicy().hasHeightForWidth())
        self.operation_date_dateEdit.setSizePolicy(sizePolicy)
        self.operation_date_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.operation_date_dateEdit.setObjectName("operation_date_dateEdit")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 171, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 231, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.contracts_combobox = QtWidgets.QComboBox(self.tab)
        self.contracts_combobox.setGeometry(QtCore.QRect(330, 180, 421, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contracts_combobox.sizePolicy().hasHeightForWidth())
        self.contracts_combobox.setSizePolicy(sizePolicy)
        self.contracts_combobox.setObjectName("contracts_combobox")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(330, 160, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 60, 231, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.detection_date_dateEdit = QtWidgets.QDateEdit(self.tab)
        self.detection_date_dateEdit.setGeometry(QtCore.QRect(170, 100, 101, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detection_date_dateEdit.sizePolicy().hasHeightForWidth())
        self.detection_date_dateEdit.setSizePolicy(sizePolicy)
        self.detection_date_dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.detection_date_dateEdit.setObjectName("detection_date_dateEdit")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(40, 80, 121, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(170, 80, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.payment_purpose_combobox = QtWidgets.QComboBox(self.tab)
        self.payment_purpose_combobox.setGeometry(QtCore.QRect(40, 160, 231, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.payment_purpose_combobox.sizePolicy().hasHeightForWidth())
        self.payment_purpose_combobox.setSizePolicy(sizePolicy)
        self.payment_purpose_combobox.setObjectName("payment_purpose_combobox")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(40, 140, 131, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(40, 190, 231, 121))
        self.plainTextEdit.setObjectName("plainEdit")
        self.insert_button = QtWidgets.QPushButton(self.tab)
        self.insert_button.setGeometry(QtCore.QRect(330, 210, 141, 23))
        self.insert_button.setObjectName("insert_button")
        self.insert_button.clicked.connect(self.insert_into_db_button)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("")
        self.tabWidget.addTab(self.tab_2, "")
        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)



        self.debtor_combobox.addItems(queries.get_all_participants())
        self.receiver_combobox.addItems(queries.get_all_participants())
        self.payer_combobox.addItems(queries.get_all_participants())
        self.contracts_combobox.currentTextChanged.connect(self.show_payment_purpose)
        
        self.debtor_combobox.currentIndexChanged.connect(self.show_new_contracts)
        self.payer_combobox.currentIndexChanged.connect(self.show_new_contracts)
        self.receiver_combobox.currentIndexChanged.connect(self.show_new_contracts)
        
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Должник"))
        self.label_2.setText(_translate("Dialog", "Получатель"))
        self.label_3.setText(_translate("Dialog", "Плательщик"))
        self.label_4.setText(_translate("Dialog", "Сведения об операции"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Сумма операции"))
        self.label_5.setText(_translate("Dialog", "Договор"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Номер платежа"))
        self.plainTextEdit.setPlaceholderText(_translate("Dialog", "Назначение платежа"))
        self.label_6.setText(_translate("Dialog", "Совершение операции"))
        self.label_7.setText(_translate("Dialog", "Обнаружение операции"))
        self.label_8.setText(_translate("Dialog", "Назначение платежа"))
        self.insert_button.setText(_translate("Dialog", "Внести в базу"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))
        
  
    def insert_into_db_button(self):
        operation_object = queries.OperationObjectFactory().create_last_operation_object()        
        operation_date=self.operation_date_dateEdit.text()
        detection_date=self.detection_date_dateEdit.text()
        daily_number=operation_object.make_new_daily_number()
        annual_number=operation_object.make_next_annual_number()
        operation_number=operation_object.make_next_operation_number()
        amount=self.lineEdit.text()
        payment_purpose=self.plainTextEdit.toPlainText()
        payment_class=self.plainTextEdit.toPlainText()
        payer=queries.get_org_id_by_org_name(self.payer_combobox.currentText())
        debtor=queries.get_org_id_by_org_name(self.debtor_combobox.currentText())
        receiver=queries.get_org_id_by_org_name(self.receiver_combobox.currentText())
        contract=self.contracts_combobox.currentText()
        payment_number=self.lineEdit_2.text()
        queries.insert_operation(operation_date, detection_date, daily_number, annual_number, operation_number, amount, payment_purpose, payment_class,
                     payment_number, payer, debtor, receiver, contract)
    
    def show_new_text(self):
        self.textEdit.setText(str(self.payment_purpose_combobox.currentText()))
        
    def show_payment_purpose(self):
        self.payment_purpose_combobox.clear()
        self.payment_purpose_combobox.addItems(queries.get_all_payment_purposes(self.contracts_combobox.currentText()))
        self.plainTextEdit.clear()
        self.plainTextEdit.appendPlainText(str(self.payment_purpose_combobox.currentText()))
    
    def show_new_contracts(self):
        self.contracts_combobox.clear()
        self.contracts_combobox.addItems(queries.get_all_contracts_depending_on_sides(self.debtor_combobox.currentText(), 
                                                                                      self.payer_combobox.currentText(), 
                                                                                      self.receiver_combobox.currentText()))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
sys.exit(app.exec_())        