import sip
sip.setapi('QString', 2)
from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd
from lxml import etree
import datetime



orglist = pd.read_excel('D:/R/finmon/listorgs.xlsx').fillna('')
orglist_combo = list(orglist['НаимЮЛ'].astype(str))
test = ['a', 'b', 'c']


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.platelshik_label = QtWidgets.QLabel(self.centralwidget)
        self.platelshik_label.setGeometry(QtCore.QRect(21, 1, 92, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.platelshik_label.setFont(font)
        self.platelshik_label.setObjectName("platelshik_label")
        self.doljnik_label = QtWidgets.QLabel(self.centralwidget)
        self.doljnik_label.setGeometry(QtCore.QRect(20, 70, 67, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.doljnik_label.setFont(font)
        self.doljnik_label.setObjectName("doljnik_label")
        self.poluchatel_label = QtWidgets.QLabel(self.centralwidget)
        self.poluchatel_label.setGeometry(QtCore.QRect(20, 150, 87, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.poluchatel_label.setFont(font)
        self.poluchatel_label.setObjectName("poluchatel_label")
        self.poruchenie_label = QtWidgets.QLabel(self.centralwidget)
        self.poruchenie_label.setGeometry(QtCore.QRect(20, 370, 171, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.poruchenie_label.setFont(font)
        self.poruchenie_label.setObjectName("poruchenie_label")
        self.fesdate_label = QtWidgets.QLabel(self.centralwidget)
        self.fesdate_label.setGeometry(QtCore.QRect(390, 10, 92, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fesdate_label.setFont(font)
        self.fesdate_label.setObjectName("fesdate_label")
        self.operationdate_label = QtWidgets.QLabel(self.centralwidget)
        self.operationdate_label.setGeometry(QtCore.QRect(390, 80, 92, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.operationdate_label.setFont(font)
        self.operationdate_label.setObjectName("operationdate_label")
        self.FesNumberYear_label = QtWidgets.QLabel(self.centralwidget)
        self.FesNumberYear_label.setGeometry(QtCore.QRect(390, 150, 301, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FesNumberYear_label.setFont(font)
        self.FesNumberYear_label.setObjectName("FesNumberYear_label")
        self.FesNumberDay_label = QtWidgets.QLabel(self.centralwidget)
        self.FesNumberDay_label.setGeometry(QtCore.QRect(390, 210, 221, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FesNumberDay_label.setFont(font)
        self.FesNumberDay_label.setObjectName("FesNumberDay_label")
        self.Sum_label = QtWidgets.QLabel(self.centralwidget)
        self.Sum_label.setGeometry(QtCore.QRect(390, 270, 141, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Sum_label.setFont(font)
        self.Sum_label.setObjectName("Sum_label")
        self.platelshik_combo = QtWidgets.QComboBox(self.centralwidget)
        self.platelshik_combo.setGeometry(QtCore.QRect(20, 30, 211, 20))
        self.platelshik_combo.setEditable(False)
        self.platelshik_combo.setDuplicatesEnabled(True)
        self.platelshik_combo.setModelColumn(3)
        self.platelshik_combo.showPopup()
        self.platelshik_combo.setObjectName("platelshik_combo")
        self.platelshik_combo.addItems(test)
        self.doljnik_combo = QtWidgets.QComboBox(self.centralwidget)
        self.doljnik_combo.setGeometry(QtCore.QRect(20, 100, 211, 20))
        self.doljnik_combo.setEditable(False)
        self.doljnik_combo.setDuplicatesEnabled(True)
        self.doljnik_combo.setObjectName("doljnik_combo")
        self.poluchatel_combo = QtWidgets.QComboBox(self.centralwidget)
        self.poluchatel_combo.setGeometry(QtCore.QRect(20, 180, 211, 20))
        self.poluchatel_combo.setEditable(False)
        self.poluchatel_combo.setDuplicatesEnabled(True)
        self.poluchatel_combo.setObjectName("poluchatel_combo")
        self.poruchenie_text = QtWidgets.QTextEdit(self.centralwidget)
        self.poruchenie_text.setGeometry(QtCore.QRect(20, 400, 721, 71))
        self.poruchenie_text.setObjectName("poruchenie_text")
        self.sum_text = QtWidgets.QLineEdit(self.centralwidget)
        self.sum_text.setGeometry(QtCore.QRect(390, 300, 113, 20))
        self.sum_text.setObjectName("sum_text")
        self.FesNumberDay_text = QtWidgets.QLineEdit(self.centralwidget)
        self.FesNumberDay_text.setGeometry(QtCore.QRect(390, 240, 113, 20))
        self.FesNumberDay_text.setObjectName("FesNumberDay_text")
        self.FesNumberYear_text = QtWidgets.QLineEdit(self.centralwidget)
        self.FesNumberYear_text.setGeometry(QtCore.QRect(390, 180, 113, 20))
        self.FesNumberYear_text.setObjectName("FesNumberYear_text")
        self.komment_label = QtWidgets.QLabel(self.centralwidget)
        self.komment_label.setGeometry(QtCore.QRect(390, 330, 231, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.komment_label.setFont(font)
        self.komment_label.setObjectName("komment_label")
        self.komment_text = QtWidgets.QLineEdit(self.centralwidget)
        self.komment_text.setGeometry(QtCore.QRect(390, 360, 113, 20))
        self.komment_text.setObjectName("komment_text")
        self.FesDate_text = QtWidgets.QDateEdit(self.centralwidget)
        self.FesDate_text.setGeometry(QtCore.QRect(390, 40, 110, 22))
        self.FesDate_text.setObjectName("FesDate_text")
        self.OperationDate_text = QtWidgets.QDateEdit(self.centralwidget)
        self.OperationDate_text.setGeometry(QtCore.QRect(390, 110, 110, 22))
        self.OperationDate_text.setObjectName("OperationDate_text")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(20, 480, 75, 23))
        self.SaveButton.setObjectName("SaveButton")
        self.platelshik_kod_combo = QtWidgets.QComboBox(self.centralwidget)
        self.platelshik_kod_combo.setGeometry(QtCore.QRect(260, 30, 69, 22))
        self.platelshik_kod_combo.setObjectName("platelshik_kod_combo")
        self.doljnik_kod_combo = QtWidgets.QComboBox(self.centralwidget)
        self.doljnik_kod_combo.setGeometry(QtCore.QRect(260, 100, 69, 22))
        self.doljnik_kod_combo.setObjectName("doljnik_kod_combo")
        self.poluchatel_kod_combo = QtWidgets.QComboBox(self.centralwidget)
        self.poluchatel_kod_combo.setGeometry(QtCore.QRect(260, 180, 69, 22))
        self.poluchatel_kod_combo.setObjectName("poluchatel_kod_combo")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 21))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.platelshik_label.setText(_translate("MainWindow", "Плательщик"))
        self.doljnik_label.setText(_translate("MainWindow", "Должник"))
        self.poluchatel_label.setText(_translate("MainWindow", "Получатель"))
        self.poruchenie_label.setText(_translate("MainWindow", "Платежное поручение"))
        self.fesdate_label.setText(_translate("MainWindow", "Дата ФЭС"))
        self.operationdate_label.setText(_translate("MainWindow", "Дата операции"))
        self.FesNumberYear_label.setText(_translate("MainWindow", "Номер ФЭС (нарастающий с начала года)"))
        self.FesNumberDay_label.setText(_translate("MainWindow", "Номер ФЭС (на сегодня)"))
        self.Sum_label.setText(_translate("MainWindow", "Сумма операции"))
        self.komment_label.setText(_translate("MainWindow", "Номер платежного поручения"))
        self.SaveButton.setText(_translate("MainWindow", "Сохранить"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())